In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, Ridge, Lasso, LinearRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings

pd.set_option('display.max_columns', None)
np.random.seed(42)
warnings.filterwarnings('ignore')  # para deixar a saída mais limpa; remova em produção

# --- Carregamento e pré-processamento ---
df_raw = pd.read_csv('dados_consumo_simulados.csv', parse_dates=['data'], dayfirst=False)
print('Dados carregados. Linhas, colunas:', df_raw.shape)
display(df_raw.head())

# Tratamento: preencher responsavel faltante por 'desconhecido'
if 'responsavel' in df_raw.columns:
    df_raw['responsavel'] = df_raw['responsavel'].fillna('desconhecido')

# Quantidade absoluta (consumo em positivo) — mantém sinal original apenas se necessário
df_raw['quantidade_abs'] = df_raw['quantidade'].abs()

# Agrupa por unidade + material para criar agregados por par
df_agg = (
    df_raw
    .groupby(['unidade', 'material'])
    .agg(
        CONSUMO_REAL=('quantidade_abs', 'sum'),
        qtd_transacoes=('quantidade_abs', 'count'),
        media_transacao=('quantidade_abs', 'mean')
    )
    .reset_index()
)
print('\nAgregados por unidade+material:')
display(df_agg.head())

# Criando target binário: top 25% de consumo -> 1 (situação crítica / atraso)
consumo_q75 = df_agg['CONSUMO_REAL'].quantile(0.75)
df_agg['ATRASO_ENTREGA'] = (df_agg['CONSUMO_REAL'] > consumo_q75).astype(int)
print(f"\nLimite 75 percentile (CONSUMO_REAL): {consumo_q75:.2f}")
display(df_agg.head())

# --- Preparação de features ---
X = df_agg.drop(columns=['CONSUMO_REAL', 'ATRASO_ENTREGA'])
y_class = df_agg['ATRASO_ENTREGA']
y_reg = df_agg['CONSUMO_REAL']

categorical_features = ['unidade', 'material']
numerical_features = ['qtd_transacoes', 'media_transacao']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse=False), categorical_features)
    ],
    remainder='drop'
)

X_processed = preprocessor.fit_transform(X)
# Construindo nomes das features de forma segura
ohe = preprocessor.named_transformers_['cat']
ohe_feature_names = list(ohe.get_feature_names_out(categorical_features))
feature_names = numerical_features + ohe_feature_names
X_df = pd.DataFrame(X_processed, columns=feature_names)
print('\nFeatures processadas (exemplo):')
display(X_df.head())

# Divisões para classificação e regressão
try:
    X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
        X_df, y_class, test_size=0.3, random_state=42, stratify=y_class
    )
except ValueError:
    # fallback sem stratify se houver problemas (poucas amostras em uma classe)
    X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
        X_df, y_class, test_size=0.3, random_state=42
    )

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_df, y_reg, test_size=0.3, random_state=42
)

Dados carregados. Linhas, colunas: (1100, 6)

        data      unidade material   tipo  quantidade responsavel
0 2025-01-12  Santo Amaro     Tubo  saida       -5.04     Vincent
1 2025-01-12  Santo Amaro     Tubo  saida       -4.93     Vincent
2 2025-01-12  Santo Amaro     Tubo  saida       -4.95     Vincent
3 2025-01-12  Santo Amaro     Tubo  saida       -5.04     Vincent
4 2025-01-12  Santo Amaro     Tubo  saida       -5.37     Vincent

Agregados por unidade+material:

  unidade      material  CONSUMO_REAL  qtd_transacoes  media_transacao
0   Moema   Esparadrapo        617.48              70         8.821143
1   Moema          Gaze        913.45              70        13.049286
2   Moema  Medicamentos       1118.36              90        12.426222
3   Moema       Seringa        802.28              80        10.028500
4   Moema          Tubo       2795.42              70        39.934571

Limite 75 percentile (CONSUMO_REAL): 2304.53

,unidade,material,CONSUMO_REAL,qtd_transacoes,media_transacao,ATRASO_ENTREGA
0,Moema,Esparadrapo,617.48,70,8.821143,0
1,Moema,Gaze,913.45,70,13.049286,0
2,Moema,Medicamentos,1118.36,90,12.426222,0
3,Moema,Seringa,802.28,80,10.028500,0
4,Moema,Tubo,2795.42,70,39.934571,1

Features processadas (exemplo):

,qtd_transacoes,media_transacao,unidade_Moema,unidade_Morumbi,unidade_Santo Amaro,material_Esparadrapo,material_Gaze,material_Medicamentos,material_Seringa,material_Tubo
0,-0.155043,-0.723128,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,-0.155043,-0.552558,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.775217,-0.577694,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.310087,-0.674421,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.155043,0.532032,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [3]:
# --- KNN com seleção segura de K ---
from math import floor

class_counts = y_train_class.value_counts()
min_class_count = class_counts.min() if not class_counts.empty else 0
cv_value = min(5, max(2, min_class_count))  # cv entre 2 e 5, baseado na menor classe
print(f'Usando cv={cv_value} (mínimo de amostras na menor classe = {min_class_count})')

# Limitar K para não exceder o número de amostras de treino
max_k = min(15, len(X_train_class))
k_candidates = range(1, max_k + 1)
k_scores = {}

for k in k_candidates:
    # K não pode ser maior que número de amostras na classe maior do conjunto de treino
    try:
        knn = KNeighborsClassifier(n_neighbors=k)
        # Protegemos cross_val_score com try/except porque folds podem ter poucas amostras
        scores = cross_val_score(knn, X_train_class, y_train_class, cv=cv_value, scoring='accuracy')
        k_scores[k] = scores.mean()
    except Exception as e:
        # pula K inválido
        # print(f'Skipping k={k} due to error: {e}')
        continue

if not k_scores:
    best_k = 1
else:
    best_k = max(k_scores, key=k_scores.get)

print(f'K escolhido: {best_k}')

knn_model = KNeighborsClassifier(n_neighbors=best_k)
knn_model.fit(X_train_class, y_train_class)
y_pred_knn = knn_model.predict(X_test_class)

acc_knn = accuracy_score(y_test_class, y_pred_knn)
prec_knn = precision_score(y_test_class, y_pred_knn, zero_division=0)
rec_knn = recall_score(y_test_class, y_pred_knn, zero_division=0)
f1_knn = f1_score(y_test_class, y_pred_knn, zero_division=0)

print('\n--- Métricas KNN ---')
print('Acurácia:', round(acc_knn,4))
print('Precisão:', round(prec_knn,4))
print('Recall:', round(rec_knn,4))
print('F1:', round(f1_knn,4))
print('\nMatriz de Confusão:')
print(confusion_matrix(y_test_class, y_pred_knn))

Usando cv=3 (mínimo de amostras na menor classe = 3)
K escolhido: 1

--- Métricas KNN ---
Acurácia: 0.8
Precisão: 0.0
Recall: 0.0
F1: 0.0

Matriz de Confusão:
[[4 0]
 [1 0]]

In [4]:
# --- Regressão Logística (classificação interpretável) ---
logreg = LogisticRegression(solver='liblinear', random_state=42)
logreg.fit(X_train_class, y_train_class)
y_pred_logreg = logreg.predict(X_test_class)

acc_logreg = accuracy_score(y_test_class, y_pred_logreg)
prec_logreg = precision_score(y_test_class, y_pred_logreg, zero_division=0)
rec_logreg = recall_score(y_test_class, y_pred_logreg, zero_division=0)
f1_logreg = f1_score(y_test_class, y_pred_logreg, zero_division=0)

print('\n--- Métricas Regressão Logística ---')
print('Acurácia:', round(acc_logreg,4))
print('Precisão:', round(prec_logreg,4))
print('Recall:', round(rec_logreg,4))
print('F1:', round(f1_logreg,4))

# Interpretação coeficientes
coef_df = pd.DataFrame({
    'Feature': feature_names,
    'Coef': logreg.coef_[0]
})
coef_df['OddsRatio'] = np.exp(coef_df['Coef'])
coef_df = coef_df.sort_values(by='OddsRatio', ascending=False).reset_index(drop=True)
print('\nPrincipais features por Odds Ratio:')
display(coef_df.head(10))

--- Métricas Regressão Logística ---
Acurácia: 0.8
Precisão: 0.5
Recall: 1.0
F1: 0.6667

Principais features por Odds Ratio:

                 Feature      Coef  OddsRatio
0        media_transacao  1.090635   2.976163
1          material_Tubo  0.408258   1.504195
2         qtd_transacoes  0.141380   1.151862
3       material_Seringa  0.109443   1.115656
4        unidade_Morumbi  0.014546   1.014652
5          unidade_Moema -0.112138   0.893921
6  material_Medicamentos -0.131975   0.876363
7   material_Esparadrapo -0.259309   0.771585
8    unidade_Santo Amaro -0.385692   0.679980
9          material_Gaze -0.609701   0.543513

In [5]:
# --- Modelos de árvore e ensemble ---
dt = DecisionTreeClassifier(random_state=42, max_depth=5)
rf = RandomForestClassifier(random_state=42, n_estimators=100, max_depth=5)

dt.fit(X_train_class, y_train_class)
rf.fit(X_train_class, y_train_class)

metrics = []
for name, model in [('Árvore', dt), ('RandomForest', rf)]:
    y_pred = model.predict(X_test_class)
    metrics.append({
        'Modelo': name,
        'Acuracia': accuracy_score(y_test_class, y_pred),
        'F1': f1_score(y_test_class, y_pred, zero_division=0)
    })

print('\nMétricas Árvore / RandomForest:')
display(pd.DataFrame(metrics))

Métricas Árvore / RandomForest:

         Modelo  Acuracia        F1
0        Árvore       0.8  0.666667
1  RandomForest       0.8  0.666667

In [6]:
# --- Regressão: Linear, Ridge, Lasso, Polinomial ---
lin_reg = LinearRegression()
ridge = Ridge(alpha=1.0)
lasso = Lasso(alpha=1.0, max_iter=10000)

lin_reg.fit(X_train_reg, y_train_reg)
ridge.fit(X_train_reg, y_train_reg)
lasso.fit(X_train_reg, y_train_reg)

y_lin_pred = lin_reg.predict(X_test_reg)
y_ridge_pred = ridge.predict(X_test_reg)
y_lasso_pred = lasso.predict(X_test_reg)

poly = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly.fit_transform(X_train_reg)
X_test_poly = poly.transform(X_test_reg)
poly_reg = LinearRegression()
poly_reg.fit(X_train_poly, y_train_reg)
y_poly_pred = poly_reg.predict(X_test_poly)

print('\nR2 Linear:', round(r2_score(y_test_reg, y_lin_pred),4))
print('R2 Ridge:', round(r2_score(y_test_reg, y_ridge_pred),4))
print('R2 Lasso:', round(r2_score(y_test_reg, y_lasso_pred),4))
print('R2 Polinomial grau2:', round(r2_score(y_test_reg, y_poly_pred),4))

R2 Linear: -3.2587
R2 Ridge: -0.3505
R2 Lasso: -2.2719
R2 Polinomial grau2: 0.2101

In [7]:
# --- Resumo dos dados ---
print('\n--- Métricas KNN ---')
print('Acurácia:', round(acc_knn,4))
print('Precisão:', round(prec_knn,4))
print('Recall:', round(rec_knn,4))
print('F1:', round(f1_knn,4))
print('\nMatriz de Confusão:')
print(confusion_matrix(y_test_class, y_pred_knn))

print('\n--- Métricas Regressão Logística ---')
print('Acurácia:', round(acc_logreg,4))
print('Precisão:', round(prec_logreg,4))
print('Recall:', round(rec_logreg,4))
print('F1:', round(f1_logreg,4))

print('\nPrincipais features por Odds Ratio:')
display(coef_df.head(10))


print('\nMétricas Árvore / RandomForest:')
display(pd.DataFrame(metrics))

print('\nR2 Linear:', round(r2_score(y_test_reg, y_lin_pred),4))
print('R2 Ridge:', round(r2_score(y_test_reg, y_ridge_pred),4))
print('R2 Lasso:', round(r2_score(y_test_reg, y_lasso_pred),4))
print('R2 Polinomial grau2:', round(r2_score(y_test_reg, y_poly_pred),4))

--- Métricas KNN ---
Acurácia: 0.8
Precisão: 0.0
Recall: 0.0
F1: 0.0

Matriz de Confusão:
[[4 0]
 [1 0]]

--- Métricas Regressão Logística ---
Acurácia: 0.8
Precisão: 0.5
Recall: 1.0
F1: 0.6667

Principais features por Odds Ratio:

                 Feature      Coef  OddsRatio
0        media_transacao  1.090635   2.976163
1          material_Tubo  0.408258   1.504195
2         qtd_transacoes  0.141380   1.151862
3       material_Seringa  0.109443   1.115656
4        unidade_Morumbi  0.014546   1.014652
5          unidade_Moema -0.112138   0.893921
6  material_Medicamentos -0.131975   0.876363
7   material_Esparadrapo -0.259309   0.771585
8    unidade_Santo Amaro -0.385692   0.679980
9          material_Gaze -0.609701   0.543513

Métricas Árvore / RandomForest:

         Modelo  Acuracia        F1
0        Árvore       0.8  0.666667
1  RandomForest       0.8  0.666667

R2 Linear: -3.2587
R2 Ridge: -0.3505
R2 Lasso: -2.2719
R2 Polinomial grau2: 0.2101